language: php

# Specic versions
php:
- 7.0
- 5.6
- 5.5
- 5.4
- hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - mkdir -p build/logs

# Unit tests
script:
  - phpunit --coverage-clover build/logs/clover.xml