language: php

# Specic versions
php:
- 5.6
- 5.5
- hhvm

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - php composer.phar dump-autoload
  - mkdir -p build/logs

# Unit tests
script:
  - ./phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'